/*
 * Kripo API
 * API to interact with Kripo fragment, fingerprint and similarity data files.
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nl.esciencecenter.e3dchem.kripodb.ws.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * AlignedPharmacophore
 */

public class AlignedPharmacophore implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("phar")
  private String phar = null;

  @SerializedName("rmsd")
  private Double rmsd = null;

  @SerializedName("transformation_matrix")
  private List<List<Double>> transformationMatrix = new ArrayList<List<Double>>();

  public AlignedPharmacophore phar(String phar) {
    this.phar = phar;
    return this;
  }

   /**
   * Get phar
   * @return phar
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPhar() {
    return phar;
  }

  public void setPhar(String phar) {
    this.phar = phar;
  }

  public AlignedPharmacophore rmsd(Double rmsd) {
    this.rmsd = rmsd;
    return this;
  }

   /**
   * Get rmsd
   * @return rmsd
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getRmsd() {
    return rmsd;
  }

  public void setRmsd(Double rmsd) {
    this.rmsd = rmsd;
  }

  public AlignedPharmacophore transformationMatrix(List<List<Double>> transformationMatrix) {
    this.transformationMatrix = transformationMatrix;
    return this;
  }

  public AlignedPharmacophore addTransformationMatrixItem(List<Double> transformationMatrixItem) {
    this.transformationMatrix.add(transformationMatrixItem);
    return this;
  }

   /**
   * Get transformationMatrix
   * @return transformationMatrix
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public List<List<Double>> getTransformationMatrix() {
    return transformationMatrix;
  }

  public void setTransformationMatrix(List<List<Double>> transformationMatrix) {
    this.transformationMatrix = transformationMatrix;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlignedPharmacophore alignedPharmacophore = (AlignedPharmacophore) o;
    return Objects.equals(this.phar, alignedPharmacophore.phar) &&
        Objects.equals(this.rmsd, alignedPharmacophore.rmsd) &&
        Objects.equals(this.transformationMatrix, alignedPharmacophore.transformationMatrix);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phar, rmsd, transformationMatrix);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlignedPharmacophore {\n");
    
    sb.append("    phar: ").append(toIndentedString(phar)).append("\n");
    sb.append("    rmsd: ").append(toIndentedString(rmsd)).append("\n");
    sb.append("    transformationMatrix: ").append(toIndentedString(transformationMatrix)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

