/*
 * Kripo API
 * API to interact with Kripo fragment, fingerprint and similarity data files.
 *
 * OpenAPI spec version: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nl.esciencecenter.e3dchem.kripodb.ws.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import nl.esciencecenter.e3dchem.kripodb.ws.client.model.Error;
import nl.esciencecenter.e3dchem.kripodb.ws.client.model.Fragment;
import java.io.Serializable;

/**
 * FragmentsNotFound
 */

public class FragmentsNotFound implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("detail")
  private String detail = null;

  @SerializedName("status")
  private Integer status = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("absent_identifiers")
  private List<String> absentIdentifiers = new ArrayList<String>();

  @SerializedName("fragments")
  private List<Fragment> fragments = new ArrayList<Fragment>();

  public FragmentsNotFound detail(String detail) {
    this.detail = detail;
    return this;
  }

   /**
   * Get detail
   * @return detail
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getDetail() {
    return detail;
  }

  public void setDetail(String detail) {
    this.detail = detail;
  }

  public FragmentsNotFound status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public FragmentsNotFound title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public FragmentsNotFound type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public FragmentsNotFound absentIdentifiers(List<String> absentIdentifiers) {
    this.absentIdentifiers = absentIdentifiers;
    return this;
  }

  public FragmentsNotFound addAbsentIdentifiersItem(String absentIdentifiersItem) {
    this.absentIdentifiers.add(absentIdentifiersItem);
    return this;
  }

   /**
   * List of identifiers that could not be found
   * @return absentIdentifiers
  **/
  @ApiModelProperty(example = "null", required = true, value = "List of identifiers that could not be found")
  public List<String> getAbsentIdentifiers() {
    return absentIdentifiers;
  }

  public void setAbsentIdentifiers(List<String> absentIdentifiers) {
    this.absentIdentifiers = absentIdentifiers;
  }

  public FragmentsNotFound fragments(List<Fragment> fragments) {
    this.fragments = fragments;
    return this;
  }

  public FragmentsNotFound addFragmentsItem(Fragment fragmentsItem) {
    this.fragments.add(fragmentsItem);
    return this;
  }

   /**
   * Fragments that where found
   * @return fragments
  **/
  @ApiModelProperty(example = "null", required = true, value = "Fragments that where found")
  public List<Fragment> getFragments() {
    return fragments;
  }

  public void setFragments(List<Fragment> fragments) {
    this.fragments = fragments;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FragmentsNotFound fragmentsNotFound = (FragmentsNotFound) o;
    return Objects.equals(this.detail, fragmentsNotFound.detail) &&
        Objects.equals(this.status, fragmentsNotFound.status) &&
        Objects.equals(this.title, fragmentsNotFound.title) &&
        Objects.equals(this.type, fragmentsNotFound.type) &&
        Objects.equals(this.absentIdentifiers, fragmentsNotFound.absentIdentifiers) &&
        Objects.equals(this.fragments, fragmentsNotFound.fragments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(detail, status, title, type, absentIdentifiers, fragments);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FragmentsNotFound {\n");
    
    sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    absentIdentifiers: ").append(toIndentedString(absentIdentifiers)).append("\n");
    sb.append("    fragments: ").append(toIndentedString(fragments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

