/*
 * Kripo API
 * API to interact with Kripo fragment, fingerprint and similarity data files.
 *
 * OpenAPI spec version: 2.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nl.esciencecenter.e3dchem.kripodb.ws.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

/**
 * Fragment
 */

public class Fragment implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("atom_codes")
  private String atomCodes = null;

  @SerializedName("ec_number")
  private String ecNumber = null;

  @SerializedName("frag_id")
  private String fragId = null;

  @SerializedName("frag_nr")
  private Integer fragNr = null;

  @SerializedName("hash_code")
  private String hashCode = null;

  @SerializedName("het_chain")
  private String hetChain = null;

  @SerializedName("het_code")
  private String hetCode = null;

  @SerializedName("het_seq_nr")
  private Integer hetSeqNr = null;

  @SerializedName("mol")
  private String mol = null;

  @SerializedName("nr_r_groups")
  private Integer nrRGroups = null;

  @SerializedName("pdb_code")
  private String pdbCode = null;

  @SerializedName("pdb_title")
  private String pdbTitle = null;

  @SerializedName("prot_chain")
  private String protChain = null;

  @SerializedName("prot_name")
  private String protName = null;

  @SerializedName("rowid")
  private Integer rowid = null;

  @SerializedName("smiles")
  private String smiles = null;

  @SerializedName("uniprot_acc")
  private String uniprotAcc = null;

  @SerializedName("uniprot_name")
  private String uniprotName = null;

  public Fragment atomCodes(String atomCodes) {
    this.atomCodes = atomCodes;
    return this;
  }

   /**
   * Get atomCodes
   * @return atomCodes
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAtomCodes() {
    return atomCodes;
  }

  public void setAtomCodes(String atomCodes) {
    this.atomCodes = atomCodes;
  }

  public Fragment ecNumber(String ecNumber) {
    this.ecNumber = ecNumber;
    return this;
  }

   /**
   * Get ecNumber
   * @return ecNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEcNumber() {
    return ecNumber;
  }

  public void setEcNumber(String ecNumber) {
    this.ecNumber = ecNumber;
  }

  public Fragment fragId(String fragId) {
    this.fragId = fragId;
    return this;
  }

   /**
   * Fragment identifier
   * @return fragId
  **/
  @ApiModelProperty(example = "null", required = true, value = "Fragment identifier")
  public String getFragId() {
    return fragId;
  }

  public void setFragId(String fragId) {
    this.fragId = fragId;
  }

  public Fragment fragNr(Integer fragNr) {
    this.fragNr = fragNr;
    return this;
  }

   /**
   * Get fragNr
   * @return fragNr
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getFragNr() {
    return fragNr;
  }

  public void setFragNr(Integer fragNr) {
    this.fragNr = fragNr;
  }

  public Fragment hashCode(String hashCode) {
    this.hashCode = hashCode;
    return this;
  }

   /**
   * Get hashCode
   * @return hashCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getHashCode() {
    return hashCode;
  }

  public void setHashCode(String hashCode) {
    this.hashCode = hashCode;
  }

  public Fragment hetChain(String hetChain) {
    this.hetChain = hetChain;
    return this;
  }

   /**
   * Get hetChain
   * @return hetChain
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getHetChain() {
    return hetChain;
  }

  public void setHetChain(String hetChain) {
    this.hetChain = hetChain;
  }

  public Fragment hetCode(String hetCode) {
    this.hetCode = hetCode;
    return this;
  }

   /**
   * Get hetCode
   * @return hetCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getHetCode() {
    return hetCode;
  }

  public void setHetCode(String hetCode) {
    this.hetCode = hetCode;
  }

  public Fragment hetSeqNr(Integer hetSeqNr) {
    this.hetSeqNr = hetSeqNr;
    return this;
  }

   /**
   * Get hetSeqNr
   * @return hetSeqNr
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getHetSeqNr() {
    return hetSeqNr;
  }

  public void setHetSeqNr(Integer hetSeqNr) {
    this.hetSeqNr = hetSeqNr;
  }

  public Fragment mol(String mol) {
    this.mol = mol;
    return this;
  }

   /**
   * Get mol
   * @return mol
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMol() {
    return mol;
  }

  public void setMol(String mol) {
    this.mol = mol;
  }

  public Fragment nrRGroups(Integer nrRGroups) {
    this.nrRGroups = nrRGroups;
    return this;
  }

   /**
   * Get nrRGroups
   * @return nrRGroups
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getNrRGroups() {
    return nrRGroups;
  }

  public void setNrRGroups(Integer nrRGroups) {
    this.nrRGroups = nrRGroups;
  }

  public Fragment pdbCode(String pdbCode) {
    this.pdbCode = pdbCode;
    return this;
  }

   /**
   * Get pdbCode
   * @return pdbCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPdbCode() {
    return pdbCode;
  }

  public void setPdbCode(String pdbCode) {
    this.pdbCode = pdbCode;
  }

  public Fragment pdbTitle(String pdbTitle) {
    this.pdbTitle = pdbTitle;
    return this;
  }

   /**
   * Get pdbTitle
   * @return pdbTitle
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPdbTitle() {
    return pdbTitle;
  }

  public void setPdbTitle(String pdbTitle) {
    this.pdbTitle = pdbTitle;
  }

  public Fragment protChain(String protChain) {
    this.protChain = protChain;
    return this;
  }

   /**
   * Get protChain
   * @return protChain
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getProtChain() {
    return protChain;
  }

  public void setProtChain(String protChain) {
    this.protChain = protChain;
  }

  public Fragment protName(String protName) {
    this.protName = protName;
    return this;
  }

   /**
   * Get protName
   * @return protName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getProtName() {
    return protName;
  }

  public void setProtName(String protName) {
    this.protName = protName;
  }

  public Fragment rowid(Integer rowid) {
    this.rowid = rowid;
    return this;
  }

   /**
   * Get rowid
   * @return rowid
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getRowid() {
    return rowid;
  }

  public void setRowid(Integer rowid) {
    this.rowid = rowid;
  }

  public Fragment smiles(String smiles) {
    this.smiles = smiles;
    return this;
  }

   /**
   * Get smiles
   * @return smiles
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSmiles() {
    return smiles;
  }

  public void setSmiles(String smiles) {
    this.smiles = smiles;
  }

  public Fragment uniprotAcc(String uniprotAcc) {
    this.uniprotAcc = uniprotAcc;
    return this;
  }

   /**
   * Get uniprotAcc
   * @return uniprotAcc
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUniprotAcc() {
    return uniprotAcc;
  }

  public void setUniprotAcc(String uniprotAcc) {
    this.uniprotAcc = uniprotAcc;
  }

  public Fragment uniprotName(String uniprotName) {
    this.uniprotName = uniprotName;
    return this;
  }

   /**
   * Get uniprotName
   * @return uniprotName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUniprotName() {
    return uniprotName;
  }

  public void setUniprotName(String uniprotName) {
    this.uniprotName = uniprotName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Fragment fragment = (Fragment) o;
    return Objects.equals(this.atomCodes, fragment.atomCodes) &&
        Objects.equals(this.ecNumber, fragment.ecNumber) &&
        Objects.equals(this.fragId, fragment.fragId) &&
        Objects.equals(this.fragNr, fragment.fragNr) &&
        Objects.equals(this.hashCode, fragment.hashCode) &&
        Objects.equals(this.hetChain, fragment.hetChain) &&
        Objects.equals(this.hetCode, fragment.hetCode) &&
        Objects.equals(this.hetSeqNr, fragment.hetSeqNr) &&
        Objects.equals(this.mol, fragment.mol) &&
        Objects.equals(this.nrRGroups, fragment.nrRGroups) &&
        Objects.equals(this.pdbCode, fragment.pdbCode) &&
        Objects.equals(this.pdbTitle, fragment.pdbTitle) &&
        Objects.equals(this.protChain, fragment.protChain) &&
        Objects.equals(this.protName, fragment.protName) &&
        Objects.equals(this.rowid, fragment.rowid) &&
        Objects.equals(this.smiles, fragment.smiles) &&
        Objects.equals(this.uniprotAcc, fragment.uniprotAcc) &&
        Objects.equals(this.uniprotName, fragment.uniprotName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(atomCodes, ecNumber, fragId, fragNr, hashCode, hetChain, hetCode, hetSeqNr, mol, nrRGroups, pdbCode, pdbTitle, protChain, protName, rowid, smiles, uniprotAcc, uniprotName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Fragment {\n");
    
    sb.append("    atomCodes: ").append(toIndentedString(atomCodes)).append("\n");
    sb.append("    ecNumber: ").append(toIndentedString(ecNumber)).append("\n");
    sb.append("    fragId: ").append(toIndentedString(fragId)).append("\n");
    sb.append("    fragNr: ").append(toIndentedString(fragNr)).append("\n");
    sb.append("    hashCode: ").append(toIndentedString(hashCode)).append("\n");
    sb.append("    hetChain: ").append(toIndentedString(hetChain)).append("\n");
    sb.append("    hetCode: ").append(toIndentedString(hetCode)).append("\n");
    sb.append("    hetSeqNr: ").append(toIndentedString(hetSeqNr)).append("\n");
    sb.append("    mol: ").append(toIndentedString(mol)).append("\n");
    sb.append("    nrRGroups: ").append(toIndentedString(nrRGroups)).append("\n");
    sb.append("    pdbCode: ").append(toIndentedString(pdbCode)).append("\n");
    sb.append("    pdbTitle: ").append(toIndentedString(pdbTitle)).append("\n");
    sb.append("    protChain: ").append(toIndentedString(protChain)).append("\n");
    sb.append("    protName: ").append(toIndentedString(protName)).append("\n");
    sb.append("    rowid: ").append(toIndentedString(rowid)).append("\n");
    sb.append("    smiles: ").append(toIndentedString(smiles)).append("\n");
    sb.append("    uniprotAcc: ").append(toIndentedString(uniprotAcc)).append("\n");
    sb.append("    uniprotName: ").append(toIndentedString(uniprotName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

