/**
 * Kripo API
 * API to interact with Kripo fragment, fingerprint and similarity data files.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package nl.esciencecenter.e3dchem.kripodb.ws.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
/**
 * Hit
 */

public class Hit  implements Serializable {
  @SerializedName("query_frag_id")
  private String queryFragId = null;

  @SerializedName("hit_frag_id")
  private String hitFragId = null;

  @SerializedName("score")
  private Double score = null;

  public Hit queryFragId(String queryFragId) {
    this.queryFragId = queryFragId;
    return this;
  }

   /**
   * Query fragment identifier
   * @return queryFragId
  **/
  @ApiModelProperty(example = "null", value = "Query fragment identifier")
  public String getQueryFragId() {
    return queryFragId;
  }

  public void setQueryFragId(String queryFragId) {
    this.queryFragId = queryFragId;
  }

  public Hit hitFragId(String hitFragId) {
    this.hitFragId = hitFragId;
    return this;
  }

   /**
   * Hit fragment identifier
   * @return hitFragId
  **/
  @ApiModelProperty(example = "null", value = "Hit fragment identifier")
  public String getHitFragId() {
    return hitFragId;
  }

  public void setHitFragId(String hitFragId) {
    this.hitFragId = hitFragId;
  }

  public Hit score(Double score) {
    this.score = score;
    return this;
  }

   /**
   * Similarity score
   * @return score
  **/
  @ApiModelProperty(example = "null", value = "Similarity score")
  public Double getScore() {
    return score;
  }

  public void setScore(Double score) {
    this.score = score;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Hit hit = (Hit) o;
    return Objects.equals(this.queryFragId, hit.queryFragId) &&
        Objects.equals(this.hitFragId, hit.hitFragId) &&
        Objects.equals(this.score, hit.score);
  }

  @Override
  public int hashCode() {
    return Objects.hash(queryFragId, hitFragId, score);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Hit {\n");
    
    sb.append("    queryFragId: ").append(toIndentedString(queryFragId)).append("\n");
    sb.append("    hitFragId: ").append(toIndentedString(hitFragId)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

